---
title: "Final_Draft"
author: "Franca Kaba Gómez"
date: "2025-06-22"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(decisionSupport)
library(ggplot2)
library(kableExtra)
library(ggplot2)
library(plyr)
library(dplyr)
```

##Introduction  
## Variables  

```{r variables, echo=FALSE}
Variables_Cocoa_Conventional<-read.csv("Variables_Cocoa_Conventional.csv", row.names = 1)
knitr::kable(Variables_Cocoa_Conventional)%>%
  kable_classic(full_width = F, html_font = "Cambria")
make_variables <- function(est,n=1)
{ x<-random(rho=est, n=n)
for(i in colnames(x)) assign(i,
                             as.numeric(x[1,i]),envir=.GlobalEnv)
}

```
```{r include=FALSE}
make_variables(as.estimate(Variables_Cocoa_Conventional))

```

## Applying the decision support function
```{r Chance, echo = FALSE}

model_function_group52 <- function() {
  #call variables
  read.csv("Variables_Cocoa_Conventional.csv", row.names = 1)
  make_variables(as.estimate(Variables_Cocoa_Conventional))
  #creating empty variables to integrate time
  n_years <- 30
  farm_size_30 <- rep(0, n_years)
  farm_size_30 <- rep(farm_size, n_years)
  
  #risks
  dry_years <- rep(0, n_years)
  dry_years <- chance_event(
    chance = dry_year_incidence,
    value_if = 1 - dry_year_damage,
    value_if_not = 1,
    n = n_years)

  
  rainy_years <- rep(0, n_years)
  rainy_years <- chance_event(
    chance = heavy_rainfall_incidence,
    value_if = 1 - heavy_rainfall_damage,
    value_if_not = 1,
    n = n_years
  )
  
  cocoa_pest_and_diseases <- rep(0, n_years)
  cocoa_pest_and_diseases <-
    chance_event(
      chance = cocoa_pest_and_disease_incidence,
      value_if = 1 - cocoa_pest_and_disease_damage,
      value_if_not = 1,
      n = n_years
    )
  
  #costs
  labor_price_30 <- rep(0, n_years)
  labor_price_30 <- vv(labor_price, 5, n_years, relative_trend = 1)
  family_labor_30 <- rep(0, n_years)
  family_labor_30 <- rep(family_labor, n_years)
  labor_persons_full_time_30 <-
    rep(labor_persons_full_time, n_years)
  labor_persons_seasonal_30 <- rep(labor_persons_seasonal, n_years)
  
  fertilizer_cost_30 <- rep(0, n_years)
  fertilizer_cost_30 <- vv(fertilizer_cost, 20, n_years)
  fertilizer_amount_30 <- rep(0, n_years)
  fertilizer_amount_30 <- vv(fertilizer_amount, 30, n_years)
  fertilizer_effect_30 <- vv(fertilizer_effect, 10, n_years)
  
  pesticide_cost_30 <- rep(0, n_years)
  pesticide_cost_30 <- vv(pesticide_cost, 20, n_years)
  pesticide_frequency_30 <- rep(pesticide_frequency, n_years)
  
  cocoa_harvest_30 <- rep(0, n_years)
  cocoa_harvest_30 <- vv(cocoa_harvest, 5, n_years)
  
  cocoa_price_world_market_30 <- rep(0, n_years)
  cocoa_price_world_market_30 <-
    vv(cocoa_price_world_market, 30, absolute_trend = 5, n_years)
  cocoa_price_percent_farmgate_30 <- rep(0, n_years)
  cocoa_price_percent_farmgate_30 <-
    vv(cocoa_price_percent_farmgate, 10, relative_trend = 1, n_years)
  pesticide_effect_30 <- rep(0, n_years)
  pesticide_effect_30 <- rep(pesticide_effect, n_years)
  pest_increase_rain_30 <- rep(0, n_years)
  pest_increase_rain_30 <- rep(pest_increase_rain, n_years)
  
  
  #formula for the harvest considering all production risks and management options
  
  
  #calculating the actual cocoa harvest per farm
  cocoa_farm_harvest_complete <-
    farm_size * cocoa_harvest_30 * dry_years * rainy_years * cocoa_pest_and_diseases * (pesticide_frequency_30 * 1 +
                                                                                          pesticide_effect_30) * (fertilizer_amount_30 * fertilizer_effect_30)
  #income from cocoa
  income <- cocoa_farm_harvest_complete * cocoa_price_world_market_30 * cocoa_price_percent_farmgate_30
  #labor_cost
  labor_cost  <-
    labor_persons_full_time_30 * 12 * labor_price_30 + labor_persons_seasonal_30 * 5 * labor_price_30 +
    family_labor * labor_price * 12
  
  pesticide_and_fertilizer_cost <-
    pesticide_cost_30 * farm_size_30 * pesticide_frequency_30 + fertilizer_amount_30 *
    fertilizer_cost_30
  
  overall_cost <- pesticide_and_fertilizer_cost + labor_cost
  
  # Estimate the final results from the model
  final_cashflow <- income - overall_cost
  # Generate the list of outputs from the Monte Carlo simulation
  final_result_cocoa <- sum(income - overall_cost)
 return(list(final_result_cocoa = final_result_cocoa,
             final_cashflow = final_cashflow))
}


#applying the decision support package
mc_simulation2 <-
  mcSimulation(
    estimate = as.estimate(Variables_Cocoa_Conventional),
    model_function = model_function_group52,
    numberOfModelRuns = 1000,
    functionSyntax = "plainNames"
  )
plot_distributions(
  mcSimulation_object = mc_simulation2,
  vars = "final_result",
  method = "boxplot_density",
  old_names = "final_result",
  new_names = "Outcome distribution for profits"
)

```


##Making a better plot
```{r}
# Extract simulation results
simulation_df <- mc_simulation2$y
# Build the custom plot
ggplot(simulation_df, aes(x = final_result)) +
  # Density curve
  geom_density(fill = "skyblue", alpha = 0.4) +

   scale_x_continuous(labels = scales::comma)+
  theme_classic()
```
```{r}



# Plot the cashflow distribution over time

plot_cashflow(mcSimulation_object = mc_simulation2, cashflow_var_name = "final_cashflow",  x_axis_name = "Years without intervention",
              y_axis_name = "Annual cashflow in CFA",
              color_25_75 = "lightblue", color_5_95 = "lavenderblush3",
              color_median = "purple")
```
## Integration of timber trees
```{r, echo = FALSE}
Variables_intervention<-read.csv("Variables_Agroforestry_Timber_clean.csv", row.names = 1)
knitr::kable(Variables_intervention)%>%
  kable_classic(full_width = F, html_font = "Cambria")
make_variables <- function(est,n=1)
{ x<-random(rho=est, n=n)
for(i in colnames(x)) assign(i,
                             as.numeric(x[1,i]),envir=.GlobalEnv)
}
```

```{r Chance, echo = FALSE}

model_function_group53 <- function() {
  #call variables
  Variables_intervention<- read.csv("Variables_Agroforestry_Timber_clean.csv", row.names = 1)
  make_variables(as.estimate(Variables_intervention))
  #creating n_years
  n_years <- 30
  farm_size_30 <- rep(0, n_years)
  farm_size_30 <- rep(farm_size, n_years)
  
  #risks
  dry_years <- rep(0, n_years)
  dry_years <- chance_event(
    chance = dry_year_incidence,
    value_if = 1 - dry_year_damage,
    value_if_not = 1,
    n = n_years)

  
  rainy_years <- rep(0, n_years)
  rainy_years <- chance_event(
    chance = heavy_rainfall_incidence,
    value_if = 1 - heavy_rainfall_damage,
    value_if_not = 1,
    n = n_years
  )
  
  cocoa_pest_and_diseases <- rep(0, n_years)
  cocoa_pest_and_diseases <-
    chance_event(
      chance = cocoa_pest_and_disease_incidence,
      value_if = 1 - cocoa_pest_and_disease_damage,
      value_if_not = 1,
      n = n_years
    )
  
  #costs
  labor_price_30 <- rep(0, n_years)
  labor_price_30 <- vv(labor_price, 5, n_years, relative_trend = 1)
  family_labor_30 <- rep(0, n_years)
  family_labor_30 <- rep(family_labor, n_years)
  labor_persons_full_time_30 <-
    rep(labor_persons_full_time, n_years)
  labor_persons_seasonal_30 <- rep(labor_persons_seasonal, n_years)
  
  fertilizer_cost_30 <- rep(0, n_years)
  fertilizer_cost_30 <- vv(fertilizer_cost, 20, n_years)
  fertilizer_amount_30 <- rep(0, n_years)
  fertilizer_amount_30 <- vv(fertilizer_amount, 30, n_years)
  fertilizer_effect_30 <- vv(fertilizer_effect, 10, n_years)
  
  pesticide_cost_30 <- rep(0, n_years)
  pesticide_cost_30 <- vv(pesticide_cost, 20, n_years)
  pesticide_frequency_30 <- rep(pesticide_frequency, n_years)
  
  cocoa_harvest_30 <- rep(0, n_years)
  cocoa_harvest_30 <- vv(cocoa_harvest, 5, n_years)
  
  cocoa_price_world_market_30 <- rep(0, n_years)
  cocoa_price_world_market_30 <-
    vv(cocoa_price_world_market, 30, absolute_trend = 5, n_years)
  cocoa_price_percent_farmgate_30 <- rep(0, n_years)
  cocoa_price_percent_farmgate_30 <-
    vv(cocoa_price_percent_farmgate, 10, relative_trend = 1, n_years)
  pesticide_effect_30 <- rep(0, n_years)
  pesticide_effect_30 <- rep(pesticide_effect, n_years)
  pest_increase_rain_30 <- rep(0, n_years)
  pest_increase_rain_30 <- rep(pest_increase_rain, n_years)

  #labor_cost
  labor_cost  <-
    labor_persons_full_time_30 * 12 * labor_price_30 + labor_persons_seasonal_30 * 5 * labor_price_30 +
    family_labor * labor_price * 12
  
  pesticide_and_fertilizer_cost <-
    pesticide_cost_30 * farm_size_30 * pesticide_frequency_30 + fertilizer_amount_30 *
    fertilizer_cost_30
  
  overall_cost_cocoa <- pesticide_and_fertilizer_cost + labor_cost
  
  #establishment costs timber
  seedlings_cost<-c(tree_seedlings*tree_density*farm_size, rep(0, n_years-1))
  transport_cost<-c(seedling_and_equipment_transport, rep(0, n_years-1))
  establishment_labor<-c(labor_persons_establishment*(labor_price_30[1])*farm_size*3, rep(0,n_years-1))
  establishment_cost<-seedlings_cost+transport_cost+establishment_labor
  maintenance_labor_persons<-c(2*farm_size_30)
  maintenance_labor_cost<-maintenance_labor_persons*labor_price_30
  harvest_cost<-c(rep(0,n_years-1),harvest_material*labor_persons_harvest*labor_price_30[n_years]*farm_size*3)
  overall_cost_timber<-c(establishment_cost[1],maintenance_labor_cost[2:(n_years-1)],harvest_cost[n_years])
  

  #impact to cocoa production intercropped with timber
  yield_impact<-vv(impact_trees_cocoa, 10, n_years)

    #cocoa harvest
  cocoa_farm_harvest_complete <-
    farm_size_30 * cocoa_harvest_30 * dry_years * rainy_years * cocoa_pest_and_diseases * (pesticide_frequency_30 * 1 +                                                           pesticide_effect_30) * (fertilizer_amount_30 * fertilizer_effect_30)*yield_impact
  
  #income from cocoa
  income_cocoa <- cocoa_farm_harvest_complete * cocoa_price_world_market_30 * cocoa_price_percent_farmgate_30
  
  #timber_returns
  dt_timber_diameter<-vv(tree_growth_diam, 5, n_years)
  final_diameter<-60
  dt_timber_height<-vv(tree_growth_height,5,n_years)
  final_height<-sum(dt_timber_height)*100
  timber_cm3<-farm_size*tree_density*(final_diameter/2)^2*pi*final_height
  timber_m3<-timber_cm3/1000000
  income_timber<-c(rep(0,29), timber_m3*tree_price)
  
  # Estimate the final results from the model
  final_cashflow <- ((income_cocoa+income_timber) - (overall_cost_cocoa+overall_cost_timber))
  # Generate the list of outputs from the Monte Carlo simulation
  final_result <- sum(income_cocoa+income_timber - overall_cost_cocoa+overall_cost_timber)
 return(list(final_result = final_result,
             final_cashflow = final_cashflow))
}

#applying the decision support package
mc_simulation3 <-
  mcSimulation(
    estimate = as.estimate(Variables_intervention),
    model_function = model_function_group53,
    numberOfModelRuns = 1000,
    functionSyntax = "plainNames"
  )
plot_distributions(
  mcSimulation_object = mc_simulation3,
  vars = "final_result",
  method = "smooth_simple_overlay",
  old_names = "final_result",
  new_names = "Outcome distribution for profits"
)
plot_cashflow(mcSimulation_object = mc_simulation3, cashflow_var_name = "final_cashflow",  x_axis_name = "Years with intervention",
              y_axis_name = "Annual cashflow in CFA",
              color_25_75 = "lightblue", color_5_95 = "lavenderblush3",
              color_median = "purple")

```

