---
title: "Variables Group 5 (Conventional Cocoa Production)"
author: "Franca Kaba Gómez"
date: "2025-06-07"
output: html_document
bibliography: references.bib
csl: ieee-with-url.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Variables for our project

### Units:  
- kg
- ha
- USD$ / CFA -> must be denoted


#### 1. General  

farm_size <- 2-6ha (survey)
  
#### 2. Risks
dry_year_incidence <- 0-0.05  estimated from: @noauthor_world_nodate  
dry_year_damage <- 0.3-0.6  
heavy_rainfall_incidence <- 0.1-0.4  
- can we double-check this with farmers? I don't seem to find reliable data on this.
heavy_rainfall_damage 0.05-0.4  + 1.1-1.5*cocoa_pest_and_disease_incidence
- heavy rains often don't lead to losses directly, but they increase the risk for cocoa diseases
drought_incidence <- 0.01-0.1 (drought being defined as rain levels causing too low soil water content for satisfactory cocoa development)  
- can we double-check this with farmers? I don't seem to find reliable data on this.  
drought_damage <- 0.3-0.8  
cocoa_pest_and_disease_incidence <- 0.5-0.9  
- this estimate I did with rough basis on @cocoapest
cocoa_pest_and_disease_damage <- 0.05-0.8 @cocoapest  

#### 3. Costs
labor_cost  <- labor_persons_full_time*12*labor_persons_seasonal*5*labor_price
labor_price <- 30.000-100.000/month/person @wages
labor_persons_full_time  <- 0-2
labor_persons_seasonal <- 1-5 (working only during the harvest season from July-December @harvestseason )  
fertilizer_cost <- 500-1000 CFA/kg  
fertilizer_amount <-0
- I didn't find date on this :(
pesticide_cost <-23000-30500*farm_size*pesticide_frequency  
(estimated from: @cocoapesticides and adjusted for inflation with @banquemondialeWorldBank)  
pesticide_frequency<-5-15 @cocoapesticides
pesticide_effect<-0-0.028 @pesticideeffect

##### unseen labor 
family_labor<- 1-3*labor price*12  

#### 4. Benefits
cocoa_harvest  
cocoa_price_world_market = 860.74-10710.35 USD @cocoaworld  
cocoa_price_percent_farmgate = 0.45-1.1 @cocoafarmgate 
employees receive benefits
employees receive training

